# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b77e2fa0e7cf52a97739a69241084635880361f9f2b8a6ef6aa6c1180d19f2dcd4a41abac92fd992f453fd2665534ee6a6545176a37ec142d98004bce1dba09
  rakuten_app_id: <%= ENV["APP_ID"] %>
  rakuten_affiliate_id: <%= ENV["AFFILIATE_ID"] %>

test:
  secret_key_base: 003f4db4529965f1a3a4a21b5c6bfc709a17f50022e4c1000355317e999581bd0165e965aa2da9ce7996ceee77ffe6458d104343795001e385684b1ae39bf136

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  rakuten_app_id: <%= ENV["APP_ID"] %>
  rakuten_affiliate_id: <%= ENV["AFFILIATE_ID"] %>

